import isEnumValue from '../../type-guards/semantic/isEnumValue';
import type { ValidationResult } from '../../types';

/**
 * Validates that a value is one of the allowed enum values.
 *
 * Works with both string and numeric enums. For numeric enums, reverse
 * mappings generated by TypeScript are treated as valid values.
 *
 * It never throws and never mutates input.
 */
export default function validateEnumValue<T extends Record<string, unknown>>(
    enumObject: T,
    value: unknown,
    field: string,
): ValidationResult<T[keyof T]> {
    if (isEnumValue(enumObject, value)) {
        return { ok: true, value };
    }

    return {
        ok: false,
        field,
        message: 'Value must be a valid enum value',
    };
}
